server:
  port: 8080
  servlet:
    context-path: /


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: realMoney
    password: EZLJ62MRJp6atbyC
    url: jdbc:mysql://97.64.36.211/realMoney?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    show-sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis:
  type-aliases-package: com.realMoney.entity
  mapper-locations: classpath:mapper/**/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  rowBoundsWithCount: true
  offsetAsPageNum: true
logging:
  level:
    com.realMoney.mapper.*: debug
